import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Boldfit Head Caps for Men Unisex Mens Caps with Adjustable Strap in Summer for Men Caps Men for All Sports Cap For Girls caps Gym Caps for Men Women Cap Sports Caps for Men with Airholes.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "NATRAJ ART & CRAFT olid Sheesham Wood Wooden Centre Table Coffee Table Center Table Teapoy for Living Room Wooden Home Furniture.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Sony WH-1000XM4 Industry Leading Wireless Noise Cancellation Over-Ear Bluetooth Headphones with Mic,30 Hrs Battery, Multi Point-Black |Instant Bank Discount of INR 2000 on Select Prepaid transactions",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Vincent Chase By Lenskart | Gunmetal Pink Full Rim Geometric | Fashion Essentials | Branded Latest and Stylish Sunglasses | 100% UV Protected | Men & Women | Large | VC S15801.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Boldfit Head Caps for Men Unisex Mens Caps with Adjustable Strap in Summer for Men Caps Men for All Sports Cap For Girls caps Gym Caps for Men Women Cap Sports Caps for Men with Airholes.",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "NATRAJ ART & CRAFT olid Sheesham Wood Wooden Centre Table Coffee Table Center Table Teapoy for Living Room Wooden Home Furniture.",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Sony WH-1000XM4 Industry Leading Wireless Noise Cancellation Over-Ear Bluetooth Headphones with Mic,30 Hrs Battery, Multi Point-Black |Instant Bank Discount of INR 2000 on Select Prepaid transactions",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Vincent Chase By Lenskart | Gunmetal Pink Full Rim Geometric | Fashion Essentials | Branded Latest and Stylish Sunglasses | 100% UV Protected | Men & Women | Large | VC S15801.",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Flower Vase",
    price: "35.00",
    color: "Black and White",
    badge: true,
    des: "FarKraft Flower Vase | White Vase | Pampas Grass Vase | Ceramic Vase | Donut Round Shaped Vase | Home Decor Centrepiece | Decor Showpiece Donut Vase 6 Inches (Pack of 1).",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "New Backpack",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "Safari Omega 30L Laptop Backpack with Raincover, school bag for boys and girls, college bag, office bag, travel bag for men and women, Black.",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Mortar and Pestle",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Mortar and Pestle Set Stone for Spices, Okhli Masher, Khalbatta, Kharal, Mixer, Natural & Traditional Grinder and Musal, Well Design for Kitchen (Grey) (5 inch)",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "TRAVEL POINT 60 Liters Waterproof Travel Rucksack Backpack for Outdoor/Sports/Camping/Hiking/Trekking Bag for Men and Women with 1 Year Warranty (Black).",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "ADTALA Unique Design Simple Table Clock Analogue Table Clocks/Decor Clocks for Home & Office,Desk Clock 15.24 x 15.24 CM - Black Color.",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Fire-Boltt Ninja Call Pro Smart Watch Dual Chip Bluetooth Calling, 1.69 Display, AI Voice Assistance with 100 Sports Modes, with SpO2 & Heart Rate Monitoring.",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "Cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: " Tall Basket with Handles, Woven Hamper Basket for Blankets, Clothes, Large Laundry Hamper, Decorative Cute Storage Baskets for Living Room, Bedroom,(10x8, Black & Brown).",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "DearJoy Polyester Big Size Fibre Filled Stuffed Animal Elephant Soft Toy For Baby Of Plush Hugging Pillow Soft Toy For Kids Boy Girl Birthday Gift (60 Cm, Grey).",
  },
  {
    _id: 1013,
    img: newArrTwo,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "DearJoy Polyester Big Size Fibre Filled Stuffed Animal Elephant Soft Toy For Baby Of Plush Hugging Pillow Soft Toy For Kids Boy Girl Birthday Gift (60 Cm, Grey).",
  },

  {
    _id: 1014,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Fire-Boltt Ninja Call Pro Smart Watch Dual Chip Bluetooth Calling, 1.69 Display, AI Voice Assistance with 100 Sports Modes, with SpO2 & Heart Rate Monitoring.",
  },
  {
    _id: 1015,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "DearJoy Polyester Big Size Fibre Filled Stuffed Animal Elephant Soft Toy For Baby Of Plush Hugging Pillow Soft Toy For Kids Boy Girl Birthday Gift (60 Cm, Grey).",
  },
  {
    _id: 1016,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Fire-Boltt Ninja Call Pro Smart Watch Dual Chip Bluetooth Calling, 1.69 Display, AI Voice Assistance with 100 Sports Modes, with SpO2 & Heart Rate Monitoring.",
  },
  {
    _id: 1017,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "TRAVEL POINT 60 Liters Waterproof Travel Rucksack Backpack for Outdoor/Sports/Camping/Hiking/Trekking Bag for Men and Women with 1 Year Warranty (Black).",
  },
  {
    _id: 1018,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "ADTALA Unique Design Simple Table Clock Analogue Table Clocks/Decor Clocks for Home & Office,Desk Clock 15.24 x 15.24 CM - Black Color.",
  },
  {
    _id: 1019,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Fire-Boltt Ninja Call Pro Smart Watch Dual Chip Bluetooth Calling, 1.69 Display, AI Voice Assistance with 100 Sports Modes, with SpO2 & Heart Rate Monitoring.",
  },
  {
    _id: 1020,
    img: newArrThree,
    productName: "Cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Tall Basket with Handles, Woven Hamper Basket for Blankets, Clothes, Large Laundry Hamper, Decorative Cute Storage Baskets for Living Room, Bedroom,(10x8, Black & Brown).",
  },
  {
    _id: 1021,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Sony WH-1000XM4 Industry Leading Wireless Noise Cancellation Over-Ear Bluetooth Headphones with Mic,30 Hrs Battery, Multi Point-Black |Instant Bank Discount of INR 2000 on Select Prepaid transactions",
  },
  {
    _id: 1022,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Vincent Chase By Lenskart | Gunmetal Pink Full Rim Geometric | Fashion Essentials | Branded Latest and Stylish Sunglasses | 100% UV Protected | Men & Women | Large | VC S15801.",
  },
  {
    _id: 1023,
    img: bestSellerOne,
    productName: "Flower Vase",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "arKraft Flower Vase | White Vase | Pampas Grass Vase | Ceramic Vase | Donut Round Shaped Vase | Home Decor Centrepiece | Decor Showpiece Donut Vase 6 Inches (Pack of 1).",
  },
  {
    _id: 1024,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Boldfit Head Caps for Men Unisex Mens Caps with Adjustable Strap in Summer for Men Caps Men for All Sports Cap For Girls caps Gym Caps for Men Women Cap Sports Caps for Men with Airholes.",
  },
  {
    _id: 1025,
    img: spfTwo,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "NATRAJ ART & CRAFT olid Sheesham Wood Wooden Centre Table Coffee Table Center Table Teapoy for Living Room Wooden Home Furniture.",
  },
  {
    _id: 1026,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Sony WH-1000XM4 Industry Leading Wireless Noise Cancellation Over-Ear Bluetooth Headphones with Mic,30 Hrs Battery, Multi Point-Black |Instant Bank Discount of INR 2000 on Select Prepaid transactions",
  },
  {
    _id: 1027,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Vincent Chase By Lenskart | Gunmetal Pink Full Rim Geometric | Fashion Essentials | Branded Latest and Stylish Sunglasses | 100% UV Protected | Men & Women | Large | VC S15801.",
  },
  {
    _id: 1028,
    img: bestSellerOne,
    productName: "Flower Vase",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "arKraft Flower Vase | White Vase | Pampas Grass Vase | Ceramic Vase | Donut Round Shaped Vase | Home Decor Centrepiece | Decor Showpiece Donut Vase 6 Inches (Pack of 1).",
  },
  {
    _id: 1029,
    img: bestSellerTwo,
    productName: "New Backpack",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "Safari Omega 30L Laptop Backpack with Raincover, school bag for boys and girls, college bag, office bag, travel bag for men and women, Black.",
  },
  {
    _id: 1030,
    img: bestSellerThree,
    productName: "Mortar and Pestle",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Mortar and Pestle Set Stone for Spices, Okhli Masher, Khalbatta, Kharal, Mixer, Natural & Traditional Grinder and Musal, Well Design for Kitchen (Grey) (5 inch)",
  },
  {
    _id: 1031,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "TRAVEL POINT 60 Liters Waterproof Travel Rucksack Backpack for Outdoor/Sports/Camping/Hiking/Trekking Bag for Men and Women with 1 Year Warranty (Black).",
  },
  {
    _id: 1032,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "ADTALA Unique Design Simple Table Clock Analogue Table Clocks/Decor Clocks for Home & Office,Desk Clock 15.24 x 15.24 CM - Black Color.",
  },
  {
    _id: 1033,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Fire-Boltt Ninja Call Pro Smart Watch Dual Chip Bluetooth Calling, 1.69 Display, AI Voice Assistance with 100 Sports Modes, with SpO2 & Heart Rate Monitoring.",
  },
  {
    _id: 1034,
    img: newArrThree,
    productName: "Cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Tall Basket with Handles, Woven Hamper Basket for Blankets, Clothes, Large Laundry Hamper, Decorative Cute Storage Baskets for Living Room, Bedroom,(10x8, Black & Brown).",
  },
  {
    _id: 1035,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false, 
    des: "DearJoy Polyester Big Size Fibre Filled Stuffed Animal Elephant Soft Toy For Baby Of Plush Hugging Pillow Soft Toy For Kids Boy Girl Birthday Gift (60 Cm, Grey).",
  },
  {
    _id: 1036,
    img: newArrTwo,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "DearJoy Polyester Big Size Fibre Filled Stuffed Animal Elephant Soft Toy For Baby Of Plush Hugging Pillow Soft Toy For Kids Boy Girl Birthday Gift (60 Cm, Grey).",
  },
  {
    _id: 1037,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "DearJoy Polyester Big Size Fibre Filled Stuffed Animal Elephant Soft Toy For Baby Of Plush Hugging Pillow Soft Toy For Kids Boy Girl Birthday Gift (60 Cm, Grey).",
  },
  {
    _id: 1038,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Fire-Boltt Ninja Call Pro Smart Watch Dual Chip Bluetooth Calling, 1.69 Display, AI Voice Assistance with 100 Sports Modes, with SpO2 & Heart Rate Monitoring.",
  },
  {
    _id: 1039,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "TRAVEL POINT 60 Liters Waterproof Travel Rucksack Backpack for Outdoor/Sports/Camping/Hiking/Trekking Bag for Men and Women with 1 Year Warranty (Black).",
  },
  {
    _id: 1040,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "ADTALA Unique Design Simple Table Clock Analogue Table Clocks/Decor Clocks for Home & Office,Desk Clock 15.24 x 15.24 CM - Black Color.",
  },
  {
    _id: 1041,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Fire-Boltt Ninja Call Pro Smart Watch Dual Chip Bluetooth Calling, 1.69 Display, AI Voice Assistance with 100 Sports Modes, with SpO2 & Heart Rate Monitoring.",
  },
  {
    _id: 1042,
    img: newArrThree,
    productName: "Cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Tall Basket with Handles, Woven Hamper Basket for Blankets, Clothes, Large Laundry Hamper, Decorative Cute Storage Baskets for Living Room, Bedroom,(10x8, Black & Brown).",
  },
  {
    _id: 1043,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Sony WH-1000XM4 Industry Leading Wireless Noise Cancellation Over-Ear Bluetooth Headphones with Mic,30 Hrs Battery, Multi Point-Black |Instant Bank Discount of INR 2000 on Select Prepaid transactions",
  },
  {
    _id: 1044,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Vincent Chase By Lenskart | Gunmetal Pink Full Rim Geometric | Fashion Essentials | Branded Latest and Stylish Sunglasses | 100% UV Protected | Men & Women | Large | VC S15801.",
  },
  {
    _id: 1045,
    img: bestSellerOne,
    productName: "Flower Vase",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "arKraft Flower Vase | White Vase | Pampas Grass Vase | Ceramic Vase | Donut Round Shaped Vase | Home Decor Centrepiece | Decor Showpiece Donut Vase 6 Inches (Pack of 1).",
  },
  {
    _id: 1046,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Boldfit Head Caps for Men Unisex Mens Caps with Adjustable Strap in Summer for Men Caps Men for All Sports Cap For Girls caps Gym Caps for Men Women Cap Sports Caps for Men with Airholes.",
  },
];
// =================== PaginationItems End here =================
